/*******************************************************************************
 * page dynamic loading handler
 * 
 * @Generated by Tizen UI Builder
 * @Attribute managed readonly volatile
 *******************************************************************************/

// page class
/**
*  Object _cloudfunction_page()
*  @super _page
*  @constructor
*  @memberOf _cloudfunction_page 
*/
function _cloudfunction_page() {
}

//inherit _page
_cloudfunction_page.prototype = new _page("cloudfunction");

// widget assist
_cloudfunction_page.prototype.header1 = undefined;
_cloudfunction_page.prototype.heading1 = undefined;
_cloudfunction_page.prototype.formcontrol1 = undefined;
_cloudfunction_page.prototype.functionCodeInput = undefined;
_cloudfunction_page.prototype.executeFunctionButton = undefined;
_cloudfunction_page.prototype.executeAppletButton = undefined;
_cloudfunction_page.prototype.footer1 = undefined;
_cloudfunction_page.prototype.controlbar1 = undefined;
_cloudfunction_page.prototype.controlbaritem1 = undefined;
_cloudfunction_page.prototype.controlbaritem2 = undefined;
_cloudfunction_page.prototype.controlbaritem3 = undefined;
_cloudfunction_page.prototype.controlbaritem4 = undefined;
_cloudfunction_page.prototype.controlbaritem5 = undefined;

// default widget event handler
_cloudfunction_page.prototype.executeFunctionButton_ontap = function(event) {};
_cloudfunction_page.prototype.executeAppletButton_ontap = function(event) {};

_cloudfunction_page.prototype.init_page = function(isStartPage) {
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.header1 = $("#cloudfunction #header1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.heading1 = $("#cloudfunction #heading1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.formcontrol1 = $("#cloudfunction #formcontrol1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.functionCodeInput = $("#cloudfunction #functionCodeInput");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.executeFunctionButton = $("#cloudfunction #executeFunctionButton");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.executeAppletButton = $("#cloudfunction #executeAppletButton");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.footer1 = $("#cloudfunction #footer1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbar1 = $("#cloudfunction #controlbar1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbaritem1 = $("#cloudfunction #controlbaritem1");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbaritem2 = $("#cloudfunction #controlbaritem2");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbaritem3 = $("#cloudfunction #controlbaritem3");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbaritem4 = $("#cloudfunction #controlbaritem4");

		/**
		 * @type jQueryObject
		 */
		_cloudfunction_page.prototype.controlbaritem5 = $("#cloudfunction #controlbaritem5");

		// bind widget event handler
		_cloudfunction_page.prototype.executeFunctionButton.bind("tap", function(event) { _cloudfunction_page.prototype.executeFunctionButton_ontap(event); });
		_cloudfunction_page.prototype.executeAppletButton.bind("tap", function(event) { _cloudfunction_page.prototype.executeAppletButton_ontap(event); });

	}, isStartPage);

};
