/*******************************************************************************
 * page dynamic loading handler
 * 
 * @Generated by Tizen UI Builder
 * @Attribute managed readonly volatile
 *******************************************************************************/

// page class
/**
*  Object _data_page()
*  @super _page
*  @constructor
*  @memberOf _data_page 
*/
function _data_page() {
}

//inherit _page
_data_page.prototype = new _page("data");

// widget assist
_data_page.prototype.header1 = undefined;
_data_page.prototype.heading1 = undefined;
_data_page.prototype.inserObjectButton = undefined;
_data_page.prototype.insertObjectFileButton = undefined;
_data_page.prototype.searchItemsButton = undefined;
_data_page.prototype.downloadFileButton = undefined;
_data_page.prototype.footer1 = undefined;
_data_page.prototype.controlbar1 = undefined;
_data_page.prototype.controlbaritem1 = undefined;
_data_page.prototype.controlbaritem2 = undefined;
_data_page.prototype.controlbaritem3 = undefined;
_data_page.prototype.controlbaritem4 = undefined;
_data_page.prototype.controlbaritem5 = undefined;

// default widget event handler
_data_page.prototype.inserObjectButton_ontap = function(event) {};
_data_page.prototype.insertObjectFileButton_ontap = function(event) {};
_data_page.prototype.searchItemsButton_ontap = function(event) {};
_data_page.prototype.downloadFileButton_ontap = function(event) {};

_data_page.prototype.init_page = function(isStartPage) {
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.header1 = $("#data #header1");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.heading1 = $("#data #heading1");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.inserObjectButton = $("#data #inserObjectButton");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.insertObjectFileButton = $("#data #insertObjectFileButton");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.searchItemsButton = $("#data #searchItemsButton");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.downloadFileButton = $("#data #downloadFileButton");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.footer1 = $("#data #footer1");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbar1 = $("#data #controlbar1");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbaritem1 = $("#data #controlbaritem1");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbaritem2 = $("#data #controlbaritem2");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbaritem3 = $("#data #controlbaritem3");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbaritem4 = $("#data #controlbaritem4");

		/**
		 * @type jQueryObject
		 */
		_data_page.prototype.controlbaritem5 = $("#data #controlbaritem5");

		// bind widget event handler
		_data_page.prototype.inserObjectButton.bind("tap", function(event) { _data_page.prototype.inserObjectButton_ontap(event); });
		_data_page.prototype.insertObjectFileButton.bind("tap", function(event) { _data_page.prototype.insertObjectFileButton_ontap(event); });
		_data_page.prototype.searchItemsButton.bind("tap", function(event) { _data_page.prototype.searchItemsButton_ontap(event); });
		_data_page.prototype.downloadFileButton.bind("tap", function(event) { _data_page.prototype.downloadFileButton_ontap(event); });

	}, isStartPage);

};
