/*******************************************************************************
 * page dynamic loading handler
 * 
 * @Generated by Tizen UI Builder
 * @Attribute managed readonly volatile
 *******************************************************************************/

// page class
/**
*  Object _log_page()
*  @super _page
*  @constructor
*  @memberOf _log_page 
*/
function _log_page() {
}

//inherit _page
_log_page.prototype = new _page("log");

// widget assist
_log_page.prototype.header1 = undefined;
_log_page.prototype.heading1 = undefined;
_log_page.prototype.formcontrol1 = undefined;
_log_page.prototype.logMessageInput = undefined;
_log_page.prototype.logLevelInput = undefined;
_log_page.prototype.sendLogButton = undefined;
_log_page.prototype.footer1 = undefined;
_log_page.prototype.controlbar1 = undefined;
_log_page.prototype.controlbaritem1 = undefined;
_log_page.prototype.controlbaritem2 = undefined;
_log_page.prototype.controlbaritem3 = undefined;
_log_page.prototype.controlbaritem4 = undefined;
_log_page.prototype.controlbaritem5 = undefined;

// default widget event handler
_log_page.prototype.sendLogButton_ontap = function(event) {};

_log_page.prototype.init_page = function(isStartPage) {
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.header1 = $("#log #header1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.heading1 = $("#log #heading1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.formcontrol1 = $("#log #formcontrol1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.logMessageInput = $("#log #logMessageInput");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.logLevelInput = $("#log #logLevelInput");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.sendLogButton = $("#log #sendLogButton");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.footer1 = $("#log #footer1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbar1 = $("#log #controlbar1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbaritem1 = $("#log #controlbaritem1");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbaritem2 = $("#log #controlbaritem2");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbaritem3 = $("#log #controlbaritem3");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbaritem4 = $("#log #controlbaritem4");

		/**
		 * @type jQueryObject
		 */
		_log_page.prototype.controlbaritem5 = $("#log #controlbaritem5");

		// bind widget event handler
		_log_page.prototype.sendLogButton.bind("tap", function(event) { _log_page.prototype.sendLogButton_ontap(event); });

	}, isStartPage);

};
