/*******************************************************************************
 * page dynamic loading handler
 * 
 * @Generated by Tizen UI Builder
 * @Attribute managed readonly volatile
 *******************************************************************************/

// page class
/**
*  Object _settings_page()
*  @super _page
*  @constructor
*  @memberOf _settings_page 
*/
function _settings_page() {
}

//inherit _page
_settings_page.prototype = new _page("settings");

// widget assist
_settings_page.prototype.header1 = undefined;
_settings_page.prototype.formcontrol1 = undefined;
_settings_page.prototype.appCodeInput = undefined;
_settings_page.prototype.appSecretInput = undefined;
_settings_page.prototype.appPwdInput = undefined;
_settings_page.prototype.saveSettingsButton = undefined;
_settings_page.prototype.footer1 = undefined;
_settings_page.prototype.controlbar1 = undefined;
_settings_page.prototype.controlbaritem1 = undefined;
_settings_page.prototype.controlbaritem2 = undefined;
_settings_page.prototype.controlbaritem3 = undefined;
_settings_page.prototype.controlbaritem4 = undefined;
_settings_page.prototype.controlbaritem5 = undefined;

// default widget event handler
_settings_page.prototype.saveSettingsButton_ontap = function(event) {};

_settings_page.prototype.init_page = function(isStartPage) {
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.header1 = $("#settings #header1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.formcontrol1 = $("#settings #formcontrol1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.appCodeInput = $("#settings #appCodeInput");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.appSecretInput = $("#settings #appSecretInput");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.appPwdInput = $("#settings #appPwdInput");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.saveSettingsButton = $("#settings #saveSettingsButton");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.footer1 = $("#settings #footer1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbar1 = $("#settings #controlbar1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbaritem1 = $("#settings #controlbaritem1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbaritem2 = $("#settings #controlbaritem2");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbaritem3 = $("#settings #controlbaritem3");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbaritem4 = $("#settings #controlbaritem4");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.controlbaritem5 = $("#settings #controlbaritem5");

		// bind widget event handler
		_settings_page.prototype.saveSettingsButton.bind("tap", function(event) { _settings_page.prototype.saveSettingsButton_ontap(event); });

	}, isStartPage);

};
